### ISSUE TITLE
"Privacy Policy" considered "Back to Safety"

### ISSUE THREAD

**Issue by egmorant** [GoogleChrome/experience-sampling#271]
I clicked the "privacy policy" link on a malware interstitial, which launched a survey that asked why I clicked "back to safety". This should instead ask me why I chose to read the privacy policy.

**Comment by moduloprime** [comment]
good catch; I had completely overlooked the Privacy policy link on the malware warning. We shouldn't be triggering a survey on that link at all; we should wait for the user to actually respond to the warning.

Unfortunately, this may be an issue in the Chrome events API, not the extension; @adrifelt do you know?

**Comment by adrifelt** [comment]
It's an issue with the Chrome events API, not with the extension. There is a fix we could do in the extension but it's more of a heuristic than a fix. Basically we could delay the survey by a few seconds, and then wait to see whether the privacy policy loads at a known URL. If it does load, then don't show the notification. Otherwise, show the notification. It'll be imperfect but probably work most of the time.

**Comment by moduloprime** [comment]
Does the events API tell us about clicks on the Privacy policy link? I bet they're pretty rare; in practice, this may not be an issue.

**Comment by adrifelt** [comment]
No, all we know from the events API is that the warning was dismissed. We don't know that they went to the privacy policy link.

But we can look at the next URL that's loaded via the chrome.tabs API and see whether it matches the privacy policy URL, to get a rough sense.

**Comment by moduloprime** [comment]
Ok, I'm tentatively calling this a P1; I don't think it's an immediate must-fix, but would be nice to apply the heuristic.
