### ISSUE TITLE
Add validation logic to backend

### ISSUE THREAD

**Issue by adrifelt** [GoogleChrome/experience-sampling#93]
Backend should be validating fields, e.g., checking that the participant ID is an alphanumeric string of 100char.

**Comment by adrifelt** [comment]
Hi Rob, does anything actually need to be done here?
If so, can you take care of it since you're handling the backend?

**Comment by moduloprime** [comment]
This seems like a nice-to-have, but not necessary; I haven't found any problems in the backend data. Do you remember why you filed it?

**Comment by adrifelt** [comment]
because i'm a paranoid security engineer

**Comment by moduloprime** [comment]
So, you imagine this validation happening on post-processing, not before results are written to backend store? If so, I could add some validation to my python processing script.

**Comment by adrifelt** [comment]
I am remembering now that I think I saw that the backend is already doing some filtering along the liens of waht you jut described, but I am forgetting for sure. Could you double check that it does?

**Comment by christhompson** [comment]
The NDB models should enforce the types when converting a message sent to the API to a datastore object. See https://github.com/GoogleChrome/experience-sampling/blob/master/backend/models.py

This is very course-grained though. For example, participant-id is just restricted to being a StringProperty (unicode, <=500chars).

**Comment by moduloprime** [comment]
I'm looking into this

**Comment by moduloprime** [comment]
Ok, here's what I've found:
1) Chris is right; for StringProperty, the 500 char limit is checked; if a request exceeds the limit, it returns a server error
2) But you can still send an illegal participantId, e.g., with != 100 chars or with chars outside the allowed set
3) we could add validation for participantId on the backend, but I think this buys nothing, because:
  a) someone could still send an incorrect participantId that passes validation, but just isn't their ID
  b) other fields, especially the TextProperty fields for question and answer, have no length limit, and I don't know how we'd validate them
  c) I don't think we have a problem here to begin with, because we never treat the user-provided data in an executable context; i.e., it gets written as valid JSON to the backend (the server gives an error if the data provided is not valid JSON), then we read it as JSON into our post-processing script, convert it to Python dicts (where the strings are just strings, not evaluated as code), then output the dicts to CSV files, where they are, again, just strings.

So my conclusion is there's nothing to do here. I'm hardly a code injection expert, so I'm open to arguments about why I'm wrong, but if there aren't any, I'll mark this bug closed.

**Comment by moduloprime** [comment]
Hearing no objections, I'm closing this.
